name: focuzd
description: "A pomodoro app built with flutter."
publish_to: "none"

version: 1.1.1

environment:
  sdk: ">=3.4.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  yaru: ^5.1.0
  flutter_bloc: ^8.1.6
  bloc: ^8.1.4
  intl: any
  flutter_localizations:
    sdk: flutter
  handy_window: ^0.4.0
  path_provider: ^2.1.3
  path: ^1.9.0
  equatable: ^2.0.5
  desktop_notifications: ^0.6.3
  drift_sqflite: ^2.0.1
  drift: ^2.18.0
  drift_flutter: ^0.2.0
  path_to_regexp: ^0.4.0
  windows_notification: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  drift_dev: ^2.18.0
  build_runner: ^2.4.12

flutter:
  uses-material-design: true
  generate: true
