name: focuzd
description: "A pomodoro app built with flutter."
publish_to: "none"

version: 2.0.0

environment:
  sdk: ">=3.4.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  yaru: 8.1.0
  flutter_bloc: ^9.1.0
  bloc: ^9.0.0
  intl: any
  flutter_localizations:
    sdk: flutter
  handy_window: ^0.4.0
  window_manager: ^0.5.1
  path_provider: ^2.1.3
  path: ^1.9.0
  equatable: ^2.0.5
  desktop_notifications: ^0.6.3
  drift_sqflite: ^2.0.1
  drift: ^2.26.0
  drift_flutter: ^0.2.4
  path_to_regexp: ^0.4.0
  windows_notification: ^1.3.0
  duration_spinbox: ^0.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  drift_dev: ^2.26.0
  build_runner: ^2.4.15

flutter:
  uses-material-design: true
  generate: true
