name: focuzd_pomodoro_api
description: The back-end for all the functions on the app, related to pomodoro.
version: 0.0.1
publish_to: none
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ">=3.0.0 <4.0.0"

# Add regular dependencies here.
dependencies:
  path: ^1.8.0
  equatable: ^2.0.3


dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
