display_name: Focuzd
package_name: focuzd
maintainer:
  name: Peter Kal
priority: optional
section: utils
version: 1.1.1
installed_size: 6604
essential: false
icon: snap/gui/focuzd_icon.png
description: A simple and elegant pomodoro timer app.
homepage: https://github.com/peter-kal/focuzd

keywords:
  - Focuzd
  - Pomodoro
  - flutter

generic_name: Pomodoro timer app

categories:
  - Productivity
  - Utilities

startup_notify: true

# You can also specify [metainfo](https://freedesktop.org/software/appstream/docs/chap-Quickstart.html) file
# which contains metadata of the app.
# metainfo: linux/packaging/myappid.appdata.xml