name: focuzd
title: Focuzd
base: core22 
version: "0.1"
license: GPL-3.0                                                                                          
source-code: https://github.com/peter-kal/focuzd
website: https://github.com/peter-kal/focuzd
issues: https://github.com/peter-kal/focuzd/issues
icon: snap/gui/focuzd_icon.png


summary: A pomodoro app built with Flutter, and Yaru widgets.
description: |
  A new pomodoro app, built with Flutter, the goal is to make a feature-equivalent to Pomotroid. 
  Pomotroid uses electron,
  which makes it pretty heavy, slow to start, and resource
  intensive. Flutter will solve these issues while also looking nice,
  and later more features as well as more platforms will be added.
  

grade: stable
confinement: strict 
compression: lzo
architectures: 
 - build-on: amd64 
 - build-on: arm64

parts:
 flutter-git:
    source: https://github.com/flutter/flutter.git
    source-tag: 3.22.3
    source-depth: 1
    plugin: nil
    override-build: |
      mkdir -p $CRAFT_PART_INSTALL/usr/bin
      mkdir -p $CRAFT_PART_INSTALL/usr/libexec
      cp -r $CRAFT_PART_SRC $CRAFT_PART_INSTALL/usr/libexec/flutter
      ln -s $CRAFT_PART_INSTALL/usr/libexec/flutter/bin/flutter $CRAFT_PART_INSTALL/usr/bin/flutter
      ln -s $SNAPCRAFT_PART_INSTALL/usr/libexec/flutter/bin/dart $SNAPCRAFT_PART_INSTALL/usr/bin/dart
      $CRAFT_PART_INSTALL/usr/bin/flutter doctor
    build-packages:
      - clang
      - cmake
      - curl
      - libgtk-3-dev
      - ninja-build
      - unzip
      - xz-utils
      - zip
    override-prime: ''


 focuzd:
    plugin: nil
    source: https://github.com/peter-kal/focuzd.git
    after: [flutter-git]
    source-type: git 
    override-build: |
      mkdir -p $CRAFT_PART_INSTALL/bin/lib
      # work around pub get stack overflow # https://github.com/dart-lang/sdk/issues/51068#issuecomment-1396588253
      set +e
      dart pub get
      set -eux
      flutter build linux --release -v
      cp -r build/linux/*/release/bundle/* $CRAFT_PART_INSTALL/bin/


slots:
  focuzd-dbus:
   interface: dbus
   bus: session 
   name: io.peter-kal.focuzd
      
apps:
 focuzd:
  desktop: snap/gui/focuzd.desktop
  command: bin/focuzd
  extensions: [gnome]
  plugs:
    - x11
    - wayland 
    - desktop
    - desktop-legacy
    - unity7 
    - opengl
