name: focuzd
title: Focuzd
base: core24
version: "2.0"
license: GPL-3.0
source-code: https://github.com/peter-kal/focuzd
website: https://github.com/peter-kal/focuzd
issues: https://github.com/peter-kal/focuzd/issues
icon: snap/gui/focuzd_icon.png

summary: A simple and elegant pomodoro timer app.
description: |
  Focuzd is a _new_ pomodoro app, built with Flutter and Yaru theme. It provides a simple and visually pleasing UI. 
  You can change the lenght, of focus, or break periods, the number of sessions, or even make the window be always on top.
  Focuzd is **natively compiled**, far outperfoming its Electron-based alternatives1, all in a _sixth_ of the package size,
  it _integrates_ with the theme of the Desktop, providing consistency.
  Focuzd is also **strictly confined** meaning it doesn't access to things it **doesn't** need, like the internet, or system files.

  1 more comparison data on the GitHub page

grade: stable
confinement: strict
compression: lzo

platforms:
  amd64:
  arm64:

parts:
  focuzd:
    plugin: flutter
    source: https://github.com/peter-kal/focuzd.git
    flutter-target: lib/main.dart
    flutter-channel: stable
    build-packages:
      - git
slots:
  focuzd-dbus:
    interface: dbus
    bus: session
    name: io.peter-kal.focuzd

apps:
  focuzd:
    command: focuzd
    desktop: {SNAP}/meta/gui/focuzd.desktop
    extensions: [gnome]
    plugs:
      - x11
      - wayland
      - desktop
      - desktop-legacy
      - unity7
      - opengl
