name: focuzd
title: Focuzd
base: core24
version: 2.0.1
license: GPL-3.0
contact: op9h93l23@mozmail.com
source-code: https://github.com/peter-kal/focuzd
website: https://github.com/peter-kal/focuzd
issues: https://github.com/peter-kal/focuzd/issues
icon: snap/gui/focuzd_icon.png

summary: A simple and elegant pomodoro timer app.
description: |
  Focuzd is a pomodoro app built for Linux, with Flutter using the Yaru theme.
  - [x] Follow the theme of the desktop and the accent color.
  - [x] Manual Start(opt-in): manually start the focus time after a break (v2.0)
  - [x] Change the frequency of Long Breaks(v2.0)
     - [x] By Default every 4 focus times
  - [x] Language support
     - [x] English
     - [x] Spanish(v2.0)
     - [x] Greek
  - [x] Change the duration of focus, break and Long Break time. By default:
     - [x] Focus: 25 min
     - [x] Break: 5min
     - [x] Long Break: 15min
  - [x] Notifications for every new focus-break time
  - [x] Architectures
     - [x] amd64
     - [x] arm64
  - [x] Modern Infrastructure
     - [x] core24 snap(v2.0)
     - [x] Flutter 3.44.8(v2.0)
     - [x] Yaru 10.2.0(v2.0)
  - [x] Lightweight
     - [x] Package size: 13.1 MB(v2.0)
     - [x] Natively Compiled
  Suggest a feature, notify about an issue, or help with translation, in Github or mail at op9h93l23@mozmail.com .

grade: stable
confinement: strict
compression: lzo
platforms:
  amd64:
    build-on: [amd64]
    build-for: [amd64]
  arm64:
    build-on: [arm64]
    build-for: [arm64]

parts:
  flutter-git:
    source: https://github.com/flutter/flutter.git
    source-tag: 3.44.8
    source-depth: 1
    plugin: nil
    override-build: |
      mkdir -p $CRAFT_PART_INSTALL/usr/bin
      mkdir -p $CRAFT_PART_INSTALL/usr/libexec
      cp -r $CRAFT_PART_SRC $CRAFT_PART_INSTALL/usr/libexec/flutter
      ln -s $CRAFT_PART_INSTALL/usr/libexec/flutter/bin/flutter $CRAFT_PART_INSTALL/usr/bin/flutter
      ln -s $SNAPCRAFT_PART_INSTALL/usr/libexec/flutter/bin/dart $SNAPCRAFT_PART_INSTALL/usr/bin/dart
      $CRAFT_PART_INSTALL/usr/bin/flutter doctor
    build-packages:
      - clang
      - cmake
      - curl
      - libgtk-3-dev
      - ninja-build
      - unzip
      - xz-utils
      - zip
    override-prime: ""

  focuzd:
    plugin: nil
    source: https://github.com/peter-kal/focuzd.git
    source-type: git
    after: [flutter-git]
    override-build: |
      mkdir -p $CRAFT_PART_INSTALL/bin/lib
      # work around pub get stack overflow # https://github.com/dart-lang/sdk/issues/51068#issuecomment-1396588253
      set +e
      dart pub get
      set -eux
      flutter build linux --release -v
      cp -r build/linux/*/release/bundle/* $CRAFT_PART_INSTALL/bin/

slots:
  focuzd-dbus:
    interface: dbus
    bus: session
    name: io.peter-kal.focuzd

apps:
  focuzd:
    desktop: meta/gui/focuzd.desktop
    command: bin/focuzd
    extensions: [gnome]
    plugs:
      - x11
      - wayland
      - desktop
      - desktop-legacy
      - unity7
      - opengl
